# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tech-store
    username: your-username  # Thay bằng tên người dùng thực tế
    password: your-password  # Thay bằng mật khẩu thực tế
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id  # Thay bằng Client ID thực tế
            client-secret: your-google-client-secret  # Thay bằng Client Secret thực tế
            scope:
              - email
              - profile

server:
  error:
    whitelabel:
      enabled: false

bloomfilter:
  expected-users: 10000
  false-positive-probability: 0.01

jwt:
  secret: your-jwt-secret  # Thay bằng JWT secret thực tế
  expiration: 3600000    # 1 giờ
  refresh_expiration: 86400000    # 1 ngày
