# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: your_db_user
    password: your_db_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - email
              - profile

server:
  error:
    whitelabel:
      enabled: false

# JWT Configuration
jwt:
  secret: your_jwt_secret_key
  expiration: 3600000    # 1 giờ
  refresh_expiration: 86400000    # 1 ngày
